imports:
    - { resource: tables.yml }
    - { resource: triggers.yml }

services:
    stevotvr.flair.listener:
        class: stevotvr\flair\event\main_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@stevotvr.flair.operator.trigger'
            - '@stevotvr.flair.operator.user'
        tags:
            - { name: event.listener }
    stevotvr.flair.controller.acp:
        class: stevotvr\flair\controller\acp_base_controller
        abstract: true
        arguments:
            - '@service_container'
            - '@language'
            - '@request'
            - '@template'
    stevotvr.flair.controller.acp.main:
        class: stevotvr\flair\controller\acp_main_controller
        parent: stevotvr.flair.controller.acp
        calls:
            - method: setup
              arguments:
                - '@stevotvr.flair.operator.category'
                - '@stevotvr.flair.operator.flair'
    stevotvr.flair.controller.acp.cats:
        class: stevotvr\flair\controller\acp_cats_controller
        parent: stevotvr.flair.controller.acp
        calls:
            - method: setup
              arguments:
                - '@stevotvr.flair.operator.category'
    stevotvr.flair.controller.acp.flair:
        class: stevotvr\flair\controller\acp_flair_controller
        parent: stevotvr.flair.controller.acp
        calls:
            - method: setup
              arguments:
                - '@dbal.conn'
                - '@group_helper'
                - '@stevotvr.flair.operator.category'
                - '@stevotvr.flair.operator.flair'
                - '@stevotvr.flair.operator.trigger'
            - method: set_trigger_names
              arguments:
                - '@dispatcher'
                - '%stevotvr.flair.trigger_names%'
    stevotvr.flair.controller.acp.user:
        class: stevotvr\flair\controller\acp_user_controller
        parent: stevotvr.flair.controller.acp
        calls:
            - method: setup
              arguments:
                - '@config'
                - '@dbal.conn'
                - '@user'
                - '@stevotvr.flair.operator.category'
                - '@stevotvr.flair.operator.flair'
                - '@stevotvr.flair.operator.user'
            - method: set_path_info
              arguments:
                - '%core.root_path%'
                - '%core.php_ext%'
    stevotvr.flair.controller.legend:
        class: stevotvr\flair\controller\legend_controller
        arguments:
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@stevotvr.flair.operator.category'
            - '@stevotvr.flair.operator.flair'
    stevotvr.flair.entity.flair:
        class: stevotvr\flair\entity\flair
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
        calls:
            - method: setup
              arguments:
                - '@config'
    stevotvr.flair.entity.category:
        class: stevotvr\flair\entity\category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair_categories%'
    stevotvr.flair.operator:
        class: stevotvr\flair\operator\flair
        abstract: true
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.flair.tables.flair%'
            - '%stevotvr.flair.tables.flair_categories%'
            - '%stevotvr.flair.tables.flair_groups%'
            - '%stevotvr.flair.tables.flair_triggers%'
            - '%stevotvr.flair.tables.flair_users%'
    stevotvr.flair.operator.flair:
        class: stevotvr\flair\operator\flair
        parent: stevotvr.flair.operator
    stevotvr.flair.operator.category:
        class: stevotvr\flair\operator\category
        parent: stevotvr.flair.operator
    stevotvr.flair.operator.user:
        class: stevotvr\flair\operator\user
        parent: stevotvr.flair.operator
    stevotvr.flair.operator.trigger:
        class: stevotvr\flair\operator\trigger
        parent: stevotvr.flair.operator
